### ISSUE TITLE
Cannot run the project due to missing Constants

### ISSUE THREAD

**Issue by ahussein** [52North/GeoMetaFacet#3]
Creating a project of the source code in Eclipse shows errors due to missing two java file:
```
import tud.geometafacet.helper.Constants;
import tud.geometafacet.helper.INTERN;
```
These two files do not exist on the current master branch.

**Comment by Ahamann** [comment]
Here you are:
[files.zip](https://github.com/52North/GeoMetaFacet/files/1334713/files.zip)

You need to change the properties - see also the description on the front page.

**Comment by ahussein** [comment]
Thanks!
